name: CI
on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install
        uses: borales/actions-yarn@v5
        with:
          cmd: install

      - name: Check format
        uses: borales/actions-yarn@v5
        with:
          cmd: check-format

      - name: Tests
        uses: borales/actions-yarn@v5
        with:
          cmd: test

      - name: Tests
        uses: borales/actions-yarn@v5
        with:
          cmd: review

      - name: Build
        uses: borales/actions-yarn@v5
        with:
          cmd: build-all
